// <auto-generated />
using System;
using GithubDashboard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GithubDashboard.Migrations
{
    [DbContext(typeof(GithubDashboardContext))]
    [Migration("20181004053053_InitialMigrationScript")]
    partial class InitialMigrationScript
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GithubDashboard.Models.StarredRepositories", b =>
                {
                    b.Property<int>("StarredRepositoriesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Repo_id");

                    b.Property<string>("clone_url");

                    b.Property<DateTime>("created_at");

                    b.Property<string>("description");

                    b.Property<string>("html_url");

                    b.Property<string>("name");

                    b.Property<DateTime>("pushed_at");

                    b.Property<DateTime>("updated_at");

                    b.Property<string>("user_html_url");

                    b.Property<string>("user_login");

                    b.HasKey("StarredRepositoriesId");

                    b.ToTable("StarredRepositories");
                });

            modelBuilder.Entity("GithubDashboard.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("UserName");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("GithubDashboard.Models.UserRepos", b =>
                {
                    b.Property<int>("StarredRepositoriesId");

                    b.Property<int>("UserId");

                    b.HasKey("StarredRepositoriesId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRepos");
                });

            modelBuilder.Entity("GithubDashboard.Models.UserRepos", b =>
                {
                    b.HasOne("GithubDashboard.Models.StarredRepositories", "StarredRepositories")
                        .WithMany("UserRepos")
                        .HasForeignKey("StarredRepositoriesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GithubDashboard.Models.User", "User")
                        .WithMany("UserRepos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
